apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::049338438183:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-Y19IA1L03KK9
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::049338438183:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-18T09:50:49Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1500"
  uid: 6969b39c-3489-4615-915f-0fb525aedc0f
